security:
    access_control:
    - { path: ^/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }

    encoders:
        AppBundle\Entity\UserAuth:
            algorithm: bcrypt
    
    providers:
        auth_db_provider:
            entity:
                class:    AppBundle:UserAuth
                property: username

    firewalls:
        main:
            provider: auth_db_provider
            anonymous: ~
            form_login:
                login_path:                     /auth
                check_path:                     /auth
                always_use_default_target_path: false
                default_target_path:            /home/welcome
                target_path_parameter:          _target_path
            logout:
                path:   /logout
                target: /