parameters:

services:
    app.session.helper:
        class: AppBundle\Util\SessionHelper
    app.event.logger:
        class: AppBundle\Util\JourneyLogger
        arguments: ['@doctrine.orm.entity_manager']
        calls:
            - [setvalidEventTypeList ,['%valid_event_type%']]
