# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    command.import_user_csv.defaultFile: /tmp/user-data.csv

services:
    command.import_user_csv:
        class: AppBundle\Command\ImportUserCsvCommand
        tags:
            -  { name: console.command }
        arguments: ["%command.import_user_csv.defaultFile%", "import:user:csv", "Processes a CSV file and adds the users to the Database"]

    