<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * JourneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneyRepository extends EntityRepository
{
    /**
     * runa query to get an overview report of user Events
     * @return array query result
     */
    public function fetchSummaryReportByDate($date)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'select j.eventType, count(j.eventType) from AppBundle:Journey j WHERE j.eventTime LIKE :time group by j.eventType'
            )
            ->setParameter('time', $date . '%');

        return $query->getArrayResult();
    }

    /**
     * Perform a query to fetch a user's journey by email address.
     * @param  string $email user's email address
     * @return array         query result
     */
    public function fetchReportByEmail($email)
    {
        $rsm = new ResultSetMapping;
        $rsm->addScalarResult('event_type', 'event_type');
        $rsm->addScalarResult('event_time', 'event_time');

        $query = $this->getEntityManager()
            ->createNativeQuery(
                'select j.event_type as event_type, j.event_time as event_time from journey j LEFT JOIN user_auth u on u.id = j.user_id WHERE u.ua_email_address = :email ORDER by j.event_time ASC',
                $rsm
            )
            ->setParameter('email', $email);

        return $query->getArrayResult();
    }
}
